2024-05-04 16:15:57.087 | DEBUG    | common.acme:generate_and_check_acme:50 - Calling rosdiscover: ['acme', '/tmp/tmph5m5xp93.rosdiscover.yml', '--from-yml', '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.yml', '--acme', '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme', '--check', '--ignore-list', '/tmp/tmpqifkv7hzignore.txt']
2024-05-04 16:15:57.091 | INFO     | rosdiscover.acme.acme:generate_acme_file:443 - Writing Acme to /home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme
2024-05-04 16:15:57.091 | INFO     | rosdiscover.acme.acme:generate_acme_file:443 - Writing Acme to /home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme
2024-05-04 16:15:57.091 | DEBUG    | rosdiscover.acme.acme:_check_acme:457 - Running Acme checker
2024-05-04 16:15:57.091 | INFO     | rosdiscover.acme.acme:_output:448 - Checking architecture...
2024-05-04 16:15:57.093 | ERROR    | common.acme:generate_and_check_acme:54 - Failed to convert yml file to Acme for [pkg1] captured in [/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.yml]
Traceback (most recent call last):

  File "check-architecture.py", line 131, in <module>
    main()
    └ <function main at 0x7fc810770820>

  File "check-architecture.py", line 127, in main
    check(config, args.kind)
    │     │       │    └ 'observed'
    │     │       └ Namespace(configuration='fetch_lsu', experiment='experiment.yml', kind='observed', results_dir='results')
    │     └ {'type': 'recovery', 'subject': 'fetch_lsu', 'docker': {'type': 'templated', 'image': 'pkg1'}, 'distro': 'noetic', 'build_com...
    └ <function check at 0x7fc81258ef70>

  File "check-architecture.py", line 26, in check
    ({

  File "check-architecture.py", line 93, in _check_for_recovery_experiment
    generate_and_check_acme(
    └ <function generate_and_check_acme at 0x7fc811db0160>

> File "/home/az/Documents/csc7135_rosdiscover_exp/scripts/common/acme.py", line 52, in generate_and_check_acme
    rosdiscover.cli.main(args)
    │           │   │    └ ['acme', '/tmp/tmph5m5xp93.rosdiscover.yml', '--from-yml', '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subje...
    │           │   └ <function main at 0x7fc81076bee0>
    │           └ <module 'rosdiscover.cli' from '/home/az/Documents/rosdiscover/src/rosdiscover/cli.py'>
    └ <module 'rosdiscover' from '/home/az/Documents/rosdiscover/src/rosdiscover/__init__.py'>

  File "/home/az/Documents/rosdiscover/src/rosdiscover/cli.py", line 358, in main
    parsed_args.func(parsed_args)
    │           │    └ Namespace(acme='/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme', c...
    │           └ <function generate_acme at 0x7fc81076ba60>
    └ Namespace(acme='/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme', c...

  File "/home/az/Documents/rosdiscover/src/rosdiscover/cli.py", line 112, in generate_acme
    acme_gen.check_acme()
    │        └ <function AcmeGenerator.check_acme at 0x7fc81075daf0>
    └ <rosdiscover.acme.acme.AcmeGenerator object at 0x7fc8107240d0>

  File "/home/az/Documents/rosdiscover/src/rosdiscover/acme/acme.py", line 452, in check_acme
    self._check_acme(self.__acme_file)
    │    │           └ <rosdiscover.acme.acme.AcmeGenerator object at 0x7fc8107240d0>
    │    └ <function AcmeGenerator._check_acme at 0x7fc81075db80>
    └ <rosdiscover.acme.acme.AcmeGenerator object at 0x7fc8107240d0>

  File "/home/az/Documents/rosdiscover/src/rosdiscover/acme/acme.py", line 459, in _check_acme
    run = subprocess.run(list(["java", "-jar", self.__acme_jar, "-j", jf, acme_file]),
          │          │                         │                      │   └ '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme'
          │          │                         │                      └ '/tmp/tmp3ogdu7ms.json'
          │          │                         └ <rosdiscover.acme.acme.AcmeGenerator object at 0x7fc8107240d0>
          │          └ <function run at 0x7fc8124e4ee0>
          └ <module 'subprocess' from '/usr/lib/python3.8/subprocess.py'>

  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
         │      │            └ {'stdout': -1, 'stderr': -1}
         │      └ (['java', '-jar', '/home/az/Documents/rosdiscover/src/rosdiscover/acme/lib/acme.standalone-ros.jar', '-j', '/tmp/tmp3ogdu7ms....
         └ <class 'subprocess.Popen'>
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    │    │              │     │           │           └ True
    │    │              │     │           └ None
    │    │              │     └ None
    │    │              └ ['java', '-jar', '/home/az/Documents/rosdiscover/src/rosdiscover/acme/lib/acme.standalone-ros.jar', '-j', '/tmp/tmp3ogdu7ms.j...
    │    └ <function Popen._execute_child at 0x7fc812478dc0>
    └ <subprocess.Popen object at 0x7fc810724280>
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
          │                    │          │        └ 'java'
          │                    │          └ 'No such file or directory'
          │                    └ 2
          └ <class 'OSError'>

FileNotFoundError: [Errno 2] No such file or directory: 'java'
2024-05-04 16:29:26.867 | DEBUG    | common.acme:generate_and_check_acme:50 - Calling rosdiscover: ['acme', '/tmp/tmpseksfehi.rosdiscover.yml', '--from-yml', '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.yml', '--acme', '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme', '--check', '--ignore-list', '/tmp/tmpfq192_2uignore.txt']
2024-05-04 16:29:26.871 | INFO     | rosdiscover.acme.acme:generate_acme_file:443 - Writing Acme to /home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme
2024-05-04 16:29:26.871 | INFO     | rosdiscover.acme.acme:generate_acme_file:443 - Writing Acme to /home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme
2024-05-04 16:29:26.872 | DEBUG    | rosdiscover.acme.acme:_check_acme:457 - Running Acme checker
2024-05-04 16:29:26.872 | INFO     | rosdiscover.acme.acme:_output:448 - Checking architecture...
2024-05-04 16:29:26.873 | ERROR    | common.acme:generate_and_check_acme:54 - Failed to convert yml file to Acme for [pkg1] captured in [/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.yml]
Traceback (most recent call last):

  File "check-architecture.py", line 131, in <module>
    main()
    └ <function main at 0x7fcbab498820>

  File "check-architecture.py", line 127, in main
    check(config, args.kind)
    │     │       │    └ 'observed'
    │     │       └ Namespace(configuration='fetch_lsu', experiment='experiment.yml', kind='observed', results_dir='results')
    │     └ {'type': 'recovery', 'subject': 'fetch_lsu', 'docker': {'type': 'templated', 'image': 'pkg1'}, 'distro': 'noetic', 'build_com...
    └ <function check at 0x7fcbad2b9f70>

  File "check-architecture.py", line 26, in check
    ({

  File "check-architecture.py", line 93, in _check_for_recovery_experiment
    generate_and_check_acme(
    └ <function generate_and_check_acme at 0x7fcbacadb160>

> File "/home/az/Documents/csc7135_rosdiscover_exp/scripts/common/acme.py", line 52, in generate_and_check_acme
    rosdiscover.cli.main(args)
    │           │   │    └ ['acme', '/tmp/tmpseksfehi.rosdiscover.yml', '--from-yml', '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subje...
    │           │   └ <function main at 0x7fcbab494ee0>
    │           └ <module 'rosdiscover.cli' from '/home/az/Documents/rosdiscover/src/rosdiscover/cli.py'>
    └ <module 'rosdiscover' from '/home/az/Documents/rosdiscover/src/rosdiscover/__init__.py'>

  File "/home/az/Documents/rosdiscover/src/rosdiscover/cli.py", line 358, in main
    parsed_args.func(parsed_args)
    │           │    └ Namespace(acme='/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme', c...
    │           └ <function generate_acme at 0x7fcbab494a60>
    └ Namespace(acme='/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme', c...

  File "/home/az/Documents/rosdiscover/src/rosdiscover/cli.py", line 112, in generate_acme
    acme_gen.check_acme()
    │        └ <function AcmeGenerator.check_acme at 0x7fcbab488af0>
    └ <rosdiscover.acme.acme.AcmeGenerator object at 0x7fcbab456190>

  File "/home/az/Documents/rosdiscover/src/rosdiscover/acme/acme.py", line 452, in check_acme
    self._check_acme(self.__acme_file)
    │    │           └ <rosdiscover.acme.acme.AcmeGenerator object at 0x7fcbab456190>
    │    └ <function AcmeGenerator._check_acme at 0x7fcbab488b80>
    └ <rosdiscover.acme.acme.AcmeGenerator object at 0x7fcbab456190>

  File "/home/az/Documents/rosdiscover/src/rosdiscover/acme/acme.py", line 459, in _check_acme
    run = subprocess.run(list(["java", "-jar", self.__acme_jar, "-j", jf, acme_file]),
          │          │                         │                      │   └ '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme'
          │          │                         │                      └ '/tmp/tmpbb258np4.json'
          │          │                         └ <rosdiscover.acme.acme.AcmeGenerator object at 0x7fcbab456190>
          │          └ <function run at 0x7fcbad20fee0>
          └ <module 'subprocess' from '/usr/lib/python3.8/subprocess.py'>

  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
         │      │            └ {'stdout': -1, 'stderr': -1}
         │      └ (['java', '-jar', '/home/az/Documents/rosdiscover/src/rosdiscover/acme/lib/acme.standalone-ros.jar', '-j', '/tmp/tmpbb258np4....
         └ <class 'subprocess.Popen'>
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    │    │              │     │           │           └ True
    │    │              │     │           └ None
    │    │              │     └ None
    │    │              └ ['java', '-jar', '/home/az/Documents/rosdiscover/src/rosdiscover/acme/lib/acme.standalone-ros.jar', '-j', '/tmp/tmpbb258np4.j...
    │    └ <function Popen._execute_child at 0x7fcbad1a3dc0>
    └ <subprocess.Popen object at 0x7fcbab456370>
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
          │                    │          │        └ 'java'
          │                    │          └ 'No such file or directory'
          │                    └ 2
          └ <class 'OSError'>

FileNotFoundError: [Errno 2] No such file or directory: 'java'
2024-05-04 16:30:42.581 | DEBUG    | common.acme:generate_and_check_acme:50 - Calling rosdiscover: ['acme', '/tmp/tmpxm75y9nc.rosdiscover.yml', '--from-yml', '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.yml', '--acme', '/home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme', '--check', '--ignore-list', '/tmp/tmpgwmpwogcignore.txt']
2024-05-04 16:30:42.585 | INFO     | rosdiscover.acme.acme:generate_acme_file:443 - Writing Acme to /home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme
2024-05-04 16:30:42.585 | INFO     | rosdiscover.acme.acme:generate_acme_file:443 - Writing Acme to /home/az/Documents/csc7135_rosdiscover_exp/results/recovery/subjects/fetch_lsu/observed.architecture.acme
2024-05-04 16:30:42.586 | DEBUG    | rosdiscover.acme.acme:_check_acme:457 - Running Acme checker
2024-05-04 16:30:42.586 | INFO     | rosdiscover.acme.acme:_output:448 - Checking architecture...
2024-05-04 16:30:42.954 | DEBUG    | rosdiscover.acme.acme:_check_acme:462 - Checking ran successfully
2024-05-04 16:30:42.955 | DEBUG    | rosdiscover.acme.acme:_check_acme:463 - b'Acme Parser ROS Checker (release 1.0): ROS system failed to typecheck.\n'
2024-05-04 16:30:42.955 | INFO     | rosdiscover.acme.acme:_output:448 - Robot architecture has no errors
